export const strings = {
  leftBar: [
    {
      name: 'Home',
      icon: 'home',
      to: '/',
    },
    {
      name: 'Movies',
      icon: 'movie',
      to: '/movies',
    },
    {
      name: 'TV Shows',
      icon: 'tv-show',
      to: '/tv-shows',
    },
    {
      name: 'People',
      icon: 'people',
      to: '/people',
    },
    {
      name: 'More',
      icon: 'more',
      to: '/more',
    },
    {
      name: 'Add Movie',
      icon: 'add-movie',
      to: '/movies/addnew',
    },
    {
      name: 'Add TV Show',
      icon: 'add-tv-show',
      to: '/tv-shows/addnew',
    },
    {
      name: 'Settings',
      icon: 'setting',
      to: '/settings',
    },
  ],
  navButton: 'Logout',
  footerButton1: 'About TMDB',
  footerButton2: 'Contact Us',
  footerButton3: 'Support Forums',
  footerButton4: 'API',
  footerButton5: 'System Status',
  footerButton6: 'Guidelines',
  footerButton7: 'Discussions',
  footerButton8: 'Leaderboard',
  footerButton9: 'Twitter',
  footerButton10: 'Contribution Bible',
  footerButton11: 'Add New Movie',
  footerButton12: 'Add New Tv Show',
  footerButton13: 'Terms of Use',
  footerButton14: 'API Terms of Use',
  footerButton15: 'Privacy Policy',
  navLink4: '/movies/details',
  navLink5: '/tv-shows/details',
  navLink12: '/login',
  navLink13: '/signup',
  navLink14: '/about',

};
