export const strings = {
  navButton1: 'Home',
  navButton2: 'Movies',
  navButton3: 'Tv Shows',
  navButton4: 'More',
  navButton5: 'Add Movie',
  navButton6: 'Add Tv Show',
  navButton7: 'Settings',
  navButton8: 'Logout',
  
  footerButton1: 'About TMDB',
  footerButton2: 'Contact Us',
  footerButton3: 'Support Forums',
  footerButton4: 'API',
  footerButton5: 'System Status',
  footerButton6: 'Guidelines',
  footerButton7: 'Discussions',
  footerButton8: 'Leaderboard',
  footerButton9: 'Twitter',
  footerButton10: 'Contribution Bible',
  footerButton11: 'Add New Movie',
  footerButton12: 'Add New Tv Show',
  footerButton13: 'Terms of Use',
  footerButton14: 'API Terms of Use',
  footerButton15: 'Privacy Policy',
};
