export const ActionType = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  GETALLMOVIES: 'GETALLMOVIES',
  GETSTREEMINGMOVIES: 'GETSTREEMINGMOVIES',
  GETMOVIEBYNAME: 'GETMOVIEBYNAME',
  GETONRENTMOVIES: 'GETONRENTMOVIES',
  GETFORRENTMOVIES: 'GETFORRENTMOVIES',
  GETINTHEATREMOVIES: 'GETINTHEATREMOVIES',
  GETCOMINGSOONMOVIES: 'GETCOMINGSOONMOVIES',
  GETMOVIEBYDATE: 'GETMOVIEBYDATE',
};
